// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wireDemo

import (
	"toki/code-golang/wire/config"
	"toki/code-golang/wire/storage"
)

// Injectors from wire.go:

func InitializeService(path string) (*Service, error) {
	logger := config.NewLogger()
	configConfig, err := config.New(path)
	if err != nil {
		return nil, err
	}
	postgresStorage := storage.NewPostgresDB(configConfig)
	service := NewService(logger, postgresStorage)
	return service, nil
}

func InitializeMockService(path string) (*Service, error) {
	logger := config.NewLogger()
	configConfig, err := config.New(path)
	if err != nil {
		return nil, err
	}
	mockDB := storage.NewMockDB(configConfig)
	service := NewService(logger, mockDB)
	return service, nil
}
